---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
    # add code here
spec:
  template:
    # add code here
    spec:
      containers:

        - name: mysql
          image: mysql
          # this option allow to authenticate to database using user/password
          args:
            - '--default-authentication-plugin=mysql_native_password'
          # keep this settings
          securityContext:
            capabilities:
              add:
                - SYS_NICE
          env:
            # add code here
          ports:
            # add code here
