apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: app
        image: korney4eg/wordpress-empty:latest
        ports:
        - containerPort: 80
        env:
          - name: DB_NAME
            value: wordpress
          - name: DB_USER
            value: wpuser
          - name: DB_PASSWORD
            value: 'passw0rd'
          - name: DB_HOST
            value: database
          - name: DB_CHARSET
            value: utf8


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: mysql
        image: mysql
        args:
          - '--default-authentication-plugin=mysql_native_password'
        securityContext:
          capabilities:
            add:
              - SYS_NICE
        env: 
          - name: MYSQL_ROOT_PASSWORD
            value: 'p@$$w0rd'
          - name: MYSQL_DATABASE
            value: wordpress
          - name: MYSQL_USER
            value: wpuser
          - name: MYSQL_PASSWORD
            value: 'passw0rd'
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
